version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/nodejs-app

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/install.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user
